### ISSUE TITLE
Adjust spectro visualization not working when other jobs are running

### ISSUE THREAD

**Issue by MaelleTtrt** [Project-OSmOSE/osmose-toolkit#121]

**Comment by MaelleTtrt** [comment]
I launched spectrogram generation for a dataset 1 (20 Spectrogram Generator jobs). In the meanwhile, I wanted to visualize the adjsuted spectrogram from another dataset. The Adjust_spectrogram job launched and ended well (as monitored on the terminal), but when I tried visalizing the adjsut spectro, I had the following message : "Parameter adjustment is still running, come back later!".
Is this possible that the program still thinks that the param adjustemnt is still runnging because there are other jobs runnging simultaneously ?

The problem might also come from somewhere described in the out file : 
Traceback (most recent call last):
  File "/home/datawork-osmose/osmose-datarmor/source/qsub_spectrogram_generator_pkg.py", line 68, in <module>
    metadata_spectrogram = pd.read_csv(metadata_path)
  File "/home/datawork-osmose/conda-env/osmose/lib/python3.10/site-packages/pandas/util/_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "/home/datawork-osmose/conda-env/osmose/lib/python3.10/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "/home/datawork-osmose/conda-env/osmose/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 950, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/datawork-osmose/conda-env/osmose/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 605, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/datawork-osmose/conda-env/osmose/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1442, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/home/datawork-osmose/conda-env/osmose/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1735, in _make_engine
    self.handles = get_handle(
  File "/home/datawork-osmose/conda-env/osmose/lib/python3.10/site-packages/pandas/io/common.py", line 713, in get_handle
    ioargs = _get_filepath_or_buffer(
  File "/home/datawork-osmose/conda-env/osmose/lib/python3.10/site-packages/pandas/io/common.py", line 451, in _get_filepath_or_buffer
    raise ValueError(msg)
ValueError: Invalid file path or buffer object type: <class 'NoneType'>

**Comment by mathieudpnt** [comment]
After discussions, the issue seems obselete now, I close it for now but let's reopen it if the issue appears again
